apiVersion: v1
kind: Secret
metadata:
    name: myregistrykey
    namespace: default
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "dGhvbWFzcHJhZGVlcA==",
          "password": "dGhvbWFzMDZAQQ==",
          "email": "dGhvbWFzcHJhZGVlcDA2QGdtYWlsLmNvbQ==",
          "auth": "dGhvbWFzcHJhZGVlcDp0aG9tYXMwNkBB"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
